# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'btserial.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 530)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidgetCommands = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetCommands.setObjectName("listWidgetCommands")
        item = QtWidgets.QListWidgetItem()
        self.listWidgetCommands.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetCommands.addItem(item)
        self.verticalLayout_2.addWidget(self.listWidgetCommands)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonAddCommand = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAddCommand.setObjectName("pushButtonAddCommand")
        self.horizontalLayout_2.addWidget(self.pushButtonAddCommand)
        self.pushButtonAddToQueue = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAddToQueue.setObjectName("pushButtonAddToQueue")
        self.horizontalLayout_2.addWidget(self.pushButtonAddToQueue)
        self.pushButtonAddDelay = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAddDelay.setObjectName("pushButtonAddDelay")
        self.horizontalLayout_2.addWidget(self.pushButtonAddDelay)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listWidgetQueue = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetQueue.setObjectName("listWidgetQueue")
        item = QtWidgets.QListWidgetItem()
        self.listWidgetQueue.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetQueue.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetQueue.addItem(item)
        self.verticalLayout_3.addWidget(self.listWidgetQueue)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButtonMoveCommandUp = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonMoveCommandUp.setObjectName("pushButtonMoveCommandUp")
        self.horizontalLayout_3.addWidget(self.pushButtonMoveCommandUp)
        self.pushButtonMoveCommandDown = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonMoveCommandDown.setObjectName("pushButtonMoveCommandDown")
        self.horizontalLayout_3.addWidget(self.pushButtonMoveCommandDown)
        self.pushButtonDeleteCommand = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonDeleteCommand.setObjectName("pushButtonDeleteCommand")
        self.horizontalLayout_3.addWidget(self.pushButtonDeleteCommand)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButtonExecute = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonExecute.setObjectName("pushButtonExecute")
        self.horizontalLayout_4.addWidget(self.pushButtonExecute)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listWidgetLog = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetLog.setObjectName("listWidgetLog")
        item = QtWidgets.QListWidgetItem()
        item.setText("<<< Coś z robota 1")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listWidgetLog.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setText("<<< Coś z robota 2")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listWidgetLog.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setText(">>> Polecenie 1")
        font = QtGui.QFont()
        font.setItalic(True)
        item.setFont(font)
        self.listWidgetLog.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setText(">>> Polecenie 2")
        font = QtGui.QFont()
        font.setItalic(True)
        item.setFont(font)
        self.listWidgetLog.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setText("<<< Coś z robota 3")
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.listWidgetLog.addItem(item)
        self.verticalLayout_4.addWidget(self.listWidgetLog)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuProgram = QtWidgets.QMenu(self.menubar)
        self.menuProgram.setObjectName("menuProgram")
        self.menuCommands = QtWidgets.QMenu(self.menubar)
        self.menuCommands.setObjectName("menuCommands")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoadList = QtWidgets.QAction(MainWindow)
        self.actionLoadList.setObjectName("actionLoadList")
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.actionDisconnect = QtWidgets.QAction(MainWindow)
        self.actionDisconnect.setObjectName("actionDisconnect")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionQuit.setShortcut("Ctrl+Q")
        self.actionQuit.triggered.connect(qApp.quit)
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionSaveList = QtWidgets.QAction(MainWindow)
        self.actionSaveList.setObjectName("actionSaveList")
        self.menuProgram.addAction(self.actionConnect)
        self.menuProgram.addAction(self.actionDisconnect)
        self.menuProgram.addSeparator()
        self.menuProgram.addAction(self.actionSettings)
        self.menuProgram.addAction(self.actionQuit)
        self.menuCommands.addAction(self.actionLoad)
        self.menuCommands.addAction(self.actionSave)
        self.menuCommands.addSeparator()
        self.menuCommands.addAction(self.actionLoadList)
        self.menuCommands.addAction(self.actionSaveList)
        self.menubar.addAction(self.menuProgram.menuAction())
        self.menubar.addAction(self.menuCommands.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BTSerial"))
        __sortingEnabled = self.listWidgetCommands.isSortingEnabled()
        self.listWidgetCommands.setSortingEnabled(False)
        item = self.listWidgetCommands.item(0)
        item.setText(_translate("MainWindow", "Polecenie 1"))
        item = self.listWidgetCommands.item(1)
        item.setText(_translate("MainWindow", "Polecenie 2"))
        self.listWidgetCommands.setSortingEnabled(__sortingEnabled)
        self.pushButtonAddCommand.setText(_translate("MainWindow", "Add command"))
        self.pushButtonAddToQueue.setText(_translate("MainWindow", "Add to queue"))
        self.pushButtonAddDelay.setText(_translate("MainWindow", "Add delay"))
        __sortingEnabled = self.listWidgetQueue.isSortingEnabled()
        self.listWidgetQueue.setSortingEnabled(False)
        item = self.listWidgetQueue.item(0)
        item.setText(_translate("MainWindow", "Polecenie 1: parametr a"))
        item = self.listWidgetQueue.item(1)
        item.setText(_translate("MainWindow", "Polecenie 1: parametr x"))
        item = self.listWidgetQueue.item(2)
        item.setText(_translate("MainWindow", "Polecenie 2: parametr w"))
        self.listWidgetQueue.setSortingEnabled(__sortingEnabled)
        self.pushButtonMoveCommandUp.setText(_translate("MainWindow", "Move up"))
        self.pushButtonMoveCommandDown.setText(_translate("MainWindow", "Move down"))
        self.pushButtonDeleteCommand.setText(_translate("MainWindow", "Delete"))
        self.pushButtonExecute.setText(_translate("MainWindow", "Execute"))
        __sortingEnabled = self.listWidgetLog.isSortingEnabled()
        self.listWidgetLog.setSortingEnabled(False)
        self.listWidgetLog.setSortingEnabled(__sortingEnabled)
        self.menuProgram.setTitle(_translate("MainWindow", "Program"))
        self.menuCommands.setTitle(_translate("MainWindow", "Commands"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionLoadList.setText(_translate("MainWindow", "Load list"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
        self.actionDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionSaveList.setText(_translate("MainWindow", "Save list"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

