# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewCommandWidget.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BTSerialNewCommandDialog(object):
	def setupUi(self, BTSerialNewCommandDialog):
		BTSerialNewCommandDialog.setObjectName("BTSerialNewCommandDialog")
		BTSerialNewCommandDialog.resize(300, 322)
		BTSerialNewCommandDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
		BTSerialNewCommandDialog.setSizeGripEnabled(True)
		self.verticalLayout_2 = QtWidgets.QVBoxLayout(BTSerialNewCommandDialog)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.lineEditName = QtWidgets.QLineEdit(BTSerialNewCommandDialog)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lineEditName.sizePolicy().hasHeightForWidth())
		self.lineEditName.setSizePolicy(sizePolicy)
		self.lineEditName.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
		self.lineEditName.setInputMask("")
		self.lineEditName.setText("")
		self.lineEditName.setMaxLength(63)
		self.lineEditName.setFrame(True)
		self.lineEditName.setEchoMode(QtWidgets.QLineEdit.Normal)
		self.lineEditName.setClearButtonEnabled(False)
		self.lineEditName.setObjectName("lineEditName")
		self.verticalLayout_2.addWidget(self.lineEditName)
		self.lineEditDescription = QtWidgets.QLineEdit(BTSerialNewCommandDialog)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lineEditDescription.sizePolicy().hasHeightForWidth())
		self.lineEditDescription.setSizePolicy(sizePolicy)
		self.lineEditDescription.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
		self.lineEditDescription.setMaxLength(255)
		self.lineEditDescription.setObjectName("lineEditDescription")
		self.verticalLayout_2.addWidget(self.lineEditDescription)
		self.groupBoxCommandType = QtWidgets.QGroupBox(BTSerialNewCommandDialog)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.groupBoxCommandType.sizePolicy().hasHeightForWidth())
		self.groupBoxCommandType.setSizePolicy(sizePolicy)
		self.groupBoxCommandType.setAutoFillBackground(False)
		self.groupBoxCommandType.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
		self.groupBoxCommandType.setFlat(False)
		self.groupBoxCommandType.setCheckable(False)
		self.groupBoxCommandType.setObjectName("groupBoxCommandType")
		self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBoxCommandType)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.radioButtonText = QtWidgets.QRadioButton(self.groupBoxCommandType)
		self.radioButtonText.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
		self.radioButtonText.setChecked(True)
		self.radioButtonText.setObjectName("radioButtonText")
		self.horizontalLayout.addWidget(self.radioButtonText)
		self.radioButtonByte = QtWidgets.QRadioButton(self.groupBoxCommandType)
		self.radioButtonByte.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
		self.radioButtonByte.setObjectName("radioButtonByte")
		self.horizontalLayout.addWidget(self.radioButtonByte)
		self.radioButtonByte.raise_()
		self.radioButtonText.raise_()
		self.verticalLayout_2.addWidget(self.groupBoxCommandType)
		self.lineEditCodeString = QtWidgets.QLineEdit(BTSerialNewCommandDialog)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.lineEditCodeString.sizePolicy().hasHeightForWidth())
		self.lineEditCodeString.setSizePolicy(sizePolicy)
		self.lineEditCodeString.setObjectName("lineEditCodeString")
		self.verticalLayout_2.addWidget(self.lineEditCodeString)
		self.groupBoxCommandBytes = QtWidgets.QGroupBox(BTSerialNewCommandDialog)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.groupBoxCommandBytes.sizePolicy().hasHeightForWidth())
		self.groupBoxCommandBytes.setSizePolicy(sizePolicy)
		self.groupBoxCommandBytes.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
		self.groupBoxCommandBytes.setTitle("")
		self.groupBoxCommandBytes.setAlignment(QtCore.Qt.AlignCenter)
		self.groupBoxCommandBytes.setObjectName("groupBoxCommandBytes")
		self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBoxCommandBytes)
		self.horizontalLayout_3.setObjectName("horizontalLayout_3")
		self.listWidgetBytes = QtWidgets.QListWidget(self.groupBoxCommandBytes)
		self.listWidgetBytes.setEnabled(True)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.listWidgetBytes.sizePolicy().hasHeightForWidth())
		self.listWidgetBytes.setSizePolicy(sizePolicy)
		self.listWidgetBytes.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
		self.listWidgetBytes.setFrameShape(QtWidgets.QFrame.StyledPanel)
		self.listWidgetBytes.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
		self.listWidgetBytes.setProperty("showDropIndicator", False)
		self.listWidgetBytes.setObjectName("listWidgetBytes")
		self.horizontalLayout_3.addWidget(self.listWidgetBytes)
		self.verticalLayout = QtWidgets.QVBoxLayout()
		self.verticalLayout.setObjectName("verticalLayout")
		self.toolButtonAddByte = QtWidgets.QToolButton(self.groupBoxCommandBytes)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.toolButtonAddByte.sizePolicy().hasHeightForWidth())
		self.toolButtonAddByte.setSizePolicy(sizePolicy)
		self.toolButtonAddByte.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
		self.toolButtonAddByte.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
		self.toolButtonAddByte.setObjectName("toolButtonAddByte")
		self.verticalLayout.addWidget(self.toolButtonAddByte)
		self.toolButtonAddParam = QtWidgets.QToolButton(self.groupBoxCommandBytes)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.toolButtonAddParam.sizePolicy().hasHeightForWidth())
		self.toolButtonAddParam.setSizePolicy(sizePolicy)
		self.toolButtonAddParam.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
		self.toolButtonAddParam.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
		self.toolButtonAddParam.setObjectName("toolButtonAddParam")
		self.verticalLayout.addWidget(self.toolButtonAddParam)
		self.toolButtonMoveUp = QtWidgets.QToolButton(self.groupBoxCommandBytes)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.toolButtonMoveUp.sizePolicy().hasHeightForWidth())
		self.toolButtonMoveUp.setSizePolicy(sizePolicy)
		self.toolButtonMoveUp.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
		self.toolButtonMoveUp.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
		self.toolButtonMoveUp.setObjectName("toolButtonMoveUp")
		self.verticalLayout.addWidget(self.toolButtonMoveUp)
		self.toolButtonMoveDown = QtWidgets.QToolButton(self.groupBoxCommandBytes)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.toolButtonMoveDown.sizePolicy().hasHeightForWidth())
		self.toolButtonMoveDown.setSizePolicy(sizePolicy)
		self.toolButtonMoveDown.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
		self.toolButtonMoveDown.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
		self.toolButtonMoveDown.setObjectName("toolButtonMoveDown")
		self.verticalLayout.addWidget(self.toolButtonMoveDown)
		self.toolButtonRemove = QtWidgets.QToolButton(self.groupBoxCommandBytes)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.toolButtonRemove.sizePolicy().hasHeightForWidth())
		self.toolButtonRemove.setSizePolicy(sizePolicy)
		self.toolButtonRemove.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
		self.toolButtonRemove.setCheckable(False)
		self.toolButtonRemove.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
		self.toolButtonRemove.setObjectName("toolButtonRemove")
		self.verticalLayout.addWidget(self.toolButtonRemove)
		self.horizontalLayout_3.addLayout(self.verticalLayout)
		self.verticalLayout_2.addWidget(self.groupBoxCommandBytes)
		self.buttonBox = QtWidgets.QDialogButtonBox(BTSerialNewCommandDialog)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
		self.buttonBox.setSizePolicy(sizePolicy)
		self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
		self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
		self.buttonBox.setObjectName("buttonBox")
		self.verticalLayout_2.addWidget(self.buttonBox)
		self.buttonBox.raise_()
		self.groupBoxCommandType.raise_()
		self.lineEditCodeString.raise_()
		self.lineEditName.raise_()
		self.lineEditDescription.raise_()
		self.groupBoxCommandBytes.raise_()

		self.retranslateUi(BTSerialNewCommandDialog)
		self.buttonBox.accepted.connect(BTSerialNewCommandDialog.accept)
		self.buttonBox.rejected.connect(BTSerialNewCommandDialog.reject)
		QtCore.QMetaObject.connectSlotsByName(BTSerialNewCommandDialog)

	def retranslateUi(self, BTSerialNewCommandDialog):
		_translate = QtCore.QCoreApplication.translate
		BTSerialNewCommandDialog.setWindowTitle(_translate("BTSerialNewCommandDialog", "Dialog"))
		self.lineEditName.setPlaceholderText(_translate("BTSerialNewCommandDialog", "Command name"))
		self.lineEditDescription.setPlaceholderText(_translate("BTSerialNewCommandDialog", "Command description"))
		self.groupBoxCommandType.setTitle(_translate("BTSerialNewCommandDialog", "Command code type"))
		self.radioButtonText.setText(_translate("BTSerialNewCommandDialog", "Text-based"))
		self.radioButtonByte.setText(_translate("BTSerialNewCommandDialog", "Byte-based"))
		self.lineEditCodeString.setPlaceholderText(_translate("BTSerialNewCommandDialog", "Command code"))
		self.toolButtonAddByte.setText(_translate("BTSerialNewCommandDialog", "Add byte"))
		self.toolButtonAddParam.setText(_translate("BTSerialNewCommandDialog", "Add parameter"))
		self.toolButtonMoveUp.setText(_translate("BTSerialNewCommandDialog", "Move up"))
		self.toolButtonMoveDown.setText(_translate("BTSerialNewCommandDialog", "Move down"))
		self.toolButtonRemove.setText(_translate("BTSerialNewCommandDialog", "Remove"))


if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	BTSerialNewCommandDialog = QtWidgets.QDialog()
	ui = Ui_BTSerialNewCommandDialog()
	ui.setupUi(BTSerialNewCommandDialog)
	BTSerialNewCommandDialog.show()
	sys.exit(app.exec_())

